function gs_gmStateSpaceHDL_buck_convert_test1_fixpt_test_registr_setup(hFPGA)
%--------------------------------------------------------------------------
% Host Interface Script Setup
% 
% Generated with MATLAB 25.1 (R2025a) at 04:04:57 on 12/04/2026.
% This function was created for the IP Core generated from design 'gmStateSpaceHDL_buck_convert_test1_fixpt_test_registr'.
% 
% Run this function on an "fpga" object to configure it with the same interfaces as the generated IP core.
%--------------------------------------------------------------------------

%% AXI4-Lite
addAXI4SlaveInterface(hFPGA, ...
	"InterfaceID", "AXI4-Lite", ...
	"BaseAddress", 0x40430000, ...
	"AddressRange", 0x10000);

DUTPort_rst = hdlcoder.DUTPort("rst", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x100");

DUTPort_duty_open_loop = hdlcoder.DUTPort("duty_open_loop", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x104");

DUTPort_freq = hdlcoder.DUTPort("freq", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x108");

DUTPort_en = hdlcoder.DUTPort("en", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x10C");

DUTPort_mode_controller = hdlcoder.DUTPort("mode_controller", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x110");

DUTPort_vout_ref = hdlcoder.DUTPort("vout_ref", ...
	"Direction", "IN", ...
	"DataType", "uint32", ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x114");

DUTPort_vin_axi = hdlcoder.DUTPort("vin_axi", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,32,27), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x118");

DUTPort_vout_axi = hdlcoder.DUTPort("vout_axi", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,32,27), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x11C");

DUTPort_pwm_axi1 = hdlcoder.DUTPort("pwm_axi1", ...
	"Direction", "OUT", ...
	"DataType", numerictype(0,32,29), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x120");

DUTPort_error_axi2 = hdlcoder.DUTPort("error_axi2", ...
	"Direction", "OUT", ...
	"DataType", numerictype(1,32,25), ...
	"IsComplex", false, ...
	"Dimension", [1 1], ...
	"IOInterface", "AXI4-Lite", ...
	"IOInterfaceMapping", "0x124");

mapPort(hFPGA, [DUTPort_rst, DUTPort_duty_open_loop, DUTPort_freq, DUTPort_en, DUTPort_mode_controller, DUTPort_vout_ref, DUTPort_vin_axi, DUTPort_vout_axi, DUTPort_pwm_axi1, DUTPort_error_axi2]);

end
