open_system('gmStateSpaceHDL_buck_convert_test1');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Delay', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Iteration Manager/Switch1', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/State Mode Vector To Index', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/concat', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/Generate Mode Vector', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/Generate Mode Vector', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/Generate Mode Vector', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/Mode Selection/Generate Mode Vector', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Update/State Update', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Update/State Update', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Update/State Update', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Update/State Update', 'user4');
cs.HiliteType = 'user4';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'darkGreen';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gmStateSpaceHDL_buck_convert_test1/HDL Subsystem/HDL Algorithm/State Update/State Update', 'user4');
