%% =========================================================
%  SIMULATION CPU SEULE + DASHBOARD DEMO
%  Modele Buck: gmStateSpaceHDL_buck_convert_test1_fixpt_test_registr.slx
%  Modele Boost: gmStateSpaceHDL_boost_convert_fixpt.slx
%% =========================================================

clear; clc; close all;

%% -------------------------------------------------------
%  PARAMETRES
%% -------------------------------------------------------
%model_cpu = 'gmStateSpaceHDL_buck_convert_test1_fixpt_test_registr';
model_cpu = 'gmStateSpaceHDL_boost_convert_fixpt';
T_sim    = 0.0005;   % Duree de simulation [s]
Ts_blocs = '25e-9';   % Pas des blocs HDL

% Hypothese de puissance totale du laptop [W]
P_pc_W = 45.0;

% Facteur d'emission Quebec [gCO2/kWh]
CO2_factor_g_per_kWh = 1.9;

%% =========================================================
%  CALCULS PRELIMINAIRES
%% =========================================================
Ts_num = str2double(Ts_blocs);
Fs_num = 1 / Ts_num;
N_est  = round(T_sim / Ts_num);

%% =========================================================
%  CHARGEMENT MODELE
%% =========================================================
load_system(model_cpu);
set_param(model_cpu, 'FixedStep', Ts_blocs);
set_param(model_cpu, 'StopTime', num2str(T_sim));

%% =========================================================
%  MESURES AVANT
%% =========================================================
[~, mem_avant] = memory();
ram_avant_MB   = mem_avant.PhysicalMemory.Available / 1e6;
ram_totale_MB  = mem_avant.PhysicalMemory.Total / 1e6;

try
    rt         = java.lang.Runtime.getRuntime();
    cpu_coeurs = rt.availableProcessors();
catch
    cpu_coeurs = feature('numcores');
end

%% =========================================================
%  LANCEMENT SIMULATION CPU
%% =========================================================
tic;
simOut_cpu = sim(model_cpu);
t_cpu_elapsed = toc;

%% =========================================================
%  MESURES APRES
%% =========================================================
[~, mem_apres]  = memory();
ram_apres_MB    = mem_apres.PhysicalMemory.Available / 1e6;
ram_utilisee_MB = ram_avant_MB - ram_apres_MB;

t_out = simOut_cpu.tout;
if length(t_out) > 1
    Ts_reel = mean(diff(t_out));
    Fs_reel = 1 / Ts_reel;
    N_reel  = length(t_out);
else
    Ts_reel = Ts_num;
    Fs_reel = Fs_num;
    N_reel  = length(t_out);
end

%% =========================================================
%  CALCULS TEMPS REEL / ENERGIE / CO2
%% =========================================================

% Ratio CPU / temps reel
ratio_RT = t_cpu_elapsed / T_sim;

% Energie de CETTE simulation
energy_J   = P_pc_W * t_cpu_elapsed;
energy_Wh  = energy_J / 3600;
energy_kWh = energy_Wh / 1000;

% CO2 de CETTE simulation
co2_g = energy_kWh * CO2_factor_g_per_kWh;

% Projection pour 1 seconde simulee
cpu_time_for_1s = ratio_RT * 1.0;
energy_1s_J     = P_pc_W * cpu_time_for_1s;
energy_1s_Wh    = energy_1s_J / 3600;
energy_1s_kWh   = energy_1s_Wh / 1000;
co2_1s_g        = energy_1s_kWh * CO2_factor_g_per_kWh;

% Projection pour 2 secondes simulees
cpu_time_for_2s = ratio_RT * 2.0;
energy_2s_J     = P_pc_W * cpu_time_for_2s;
energy_2s_Wh    = energy_2s_J / 3600;
energy_2s_kWh   = energy_2s_Wh / 1000;
co2_2s_g        = energy_2s_kWh * CO2_factor_g_per_kWh;

%% =========================================================
%  EQUIVALENCES CO2 (APPROXIMATIONS PEDAGOGIQUES)
%% =========================================================
car_gCO2_per_km      = 192;
gasoline_gCO2_per_L  = 2310;
phone_charge_Wh      = 8;

eq_sim_km_car        = co2_g    / car_gCO2_per_km;
eq_sim_L_gasoline    = co2_g    / gasoline_gCO2_per_L;
eq_sim_phone_charges = energy_Wh / phone_charge_Wh;

eq_1s_km_car         = co2_1s_g / car_gCO2_per_km;
eq_1s_L_gasoline     = co2_1s_g / gasoline_gCO2_per_L;
eq_1s_phone_charges  = energy_1s_Wh / phone_charge_Wh;

eq_2s_km_car         = co2_2s_g / car_gCO2_per_km;
eq_2s_L_gasoline     = co2_2s_g / gasoline_gCO2_per_L;
eq_2s_phone_charges  = energy_2s_Wh / phone_charge_Wh;

%% =========================================================
%  AFFICHAGE DASHBOARD
%% =========================================================
show_results_dashboard( ...
    model_cpu, T_sim, Ts_num, Fs_num, N_est, ...
    t_cpu_elapsed, ratio_RT, ...
    Ts_reel, Fs_reel, N_reel, ...
    ram_utilisee_MB, ram_totale_MB, cpu_coeurs, ...
    P_pc_W, CO2_factor_g_per_kWh, ...
    energy_J, energy_Wh, energy_kWh, co2_g, ...
    cpu_time_for_1s, energy_1s_J, energy_1s_Wh, energy_1s_kWh, co2_1s_g, ...
    cpu_time_for_2s, energy_2s_J, energy_2s_Wh, energy_2s_kWh, co2_2s_g, ...
    eq_sim_km_car, eq_sim_L_gasoline, eq_sim_phone_charges, ...
    eq_1s_km_car, eq_1s_L_gasoline, eq_1s_phone_charges, ...
    eq_2s_km_car, eq_2s_L_gasoline, eq_2s_phone_charges);

%% =========================================================
%  FONCTION DASHBOARD
%% =========================================================
function show_results_dashboard( ...
    model_cpu, T_sim, Ts_num, Fs_num, N_est, ...
    t_cpu_elapsed, ratio_RT, ...
    Ts_reel, Fs_reel, N_reel, ...
    ram_utilisee_MB, ram_totale_MB, cpu_coeurs, ...
    P_pc_W, CO2_factor_g_per_kWh, ...
    energy_J, energy_Wh, energy_kWh, co2_g, ...
    cpu_time_for_1s, energy_1s_J, energy_1s_Wh, energy_1s_kWh, co2_1s_g, ...
    cpu_time_for_2s, energy_2s_J, energy_2s_Wh, energy_2s_kWh, co2_2s_g, ...
    eq_sim_km_car, eq_sim_L_gasoline, eq_sim_phone_charges, ...
    eq_1s_km_car, eq_1s_L_gasoline, eq_1s_phone_charges, ...
    eq_2s_km_car, eq_2s_L_gasoline, eq_2s_phone_charges)

    % Ferme ancienne fenetre
    oldFig = findall(groot, 'Type', 'Figure', 'Name', 'Résultats Simulation CPU');
    if ~isempty(oldFig); delete(oldFig); end

    %  Palette de couleurs 
    bg          = [0.95 0.96 0.98];
    panel_bg    = [1.00 1.00 1.00];
    title_col   = [0.10 0.18 0.35];
    text_col    = [0.08 0.08 0.08];
    accent_blue = [0.20 0.45 0.85];
    red_col     = [0.75 0.15 0.15];
    green_col   = [0.10 0.45 0.10];
    orange_col  = [0.70 0.35 0.00];

    %  Fenetre principale 
    fig = uifigure( ...
        'Name',     'Résultats Simulation CPU', ...
        'Position', [40 30 1600 900], ...
        'Color',    bg);

    % 
    %  TITRE + ligne décorative
    % 
    uilabel(fig, ...
        'Text',            'Dashboard — Simulation CPU / Énergie / CO2', ...
        'Position',        [30 850 900 38], ...
        'FontSize',        26, ...
        'FontWeight',      'bold', ...
        'FontColor',       title_col, ...
        'BackgroundColor', bg);

    uilabel(fig, ...
        'Text',            ' ', ...
        'Position',        [30 843 1540 2], ...
        'BackgroundColor', accent_blue);

    % 
    %  BADGE (centré en haut)
    % 
    if ratio_RT < 1
        badge_txt   = '  Plus rapide que le temps réel';
        badge_bg    = [0.83 0.95 0.84];
        badge_fc    = [0.10 0.40 0.12];
    elseif ratio_RT < 10
        badge_txt   = '  Plus lent que le temps réel';
        badge_bg    = [1.00 0.95 0.78];
        badge_fc    = [0.45 0.35 0.00];
    else
        badge_txt   = '  Très loin du temps réel';
        badge_bg    = [0.98 0.84 0.84];
        badge_fc    = [0.70 0.10 0.10];
    end

    uilabel(fig, ...
        'Text',               badge_txt, ...
        'Position',           [560 805 380 34], ...
        'FontSize',           15, ...
        'FontWeight',         'bold', ...
        'HorizontalAlignment','center', ...
        'BackgroundColor',    badge_bg, ...
        'FontColor',          badge_fc);

    % 
    %  RANGÉE DE GRANDS ENCADRÉS (ligne 1) — y = 680
    %  5 cartes : T_sim | Temps CPU total | Temps CPU 1s | Puissance | Ratio
    % 
    card_y  = 680;
    card_h  = 110;
    card_w  = 290;   % légèrement réduit pour caser 5 cartes
    gap     = 18;
    x_start = 30;

    %  Carte 1 : Durée de simulation demandée (T_sim) 
    make_card(fig, 'Durée simulée demandée (T\_sim)', ...
        sprintf('%.2e s', T_sim), ...
        x_start, card_y, card_w, card_h, ...
        panel_bg, title_col, [0.20 0.45 0.85]);   % bleu accent

    %  Carte 2 : Temps CPU total 
    make_card(fig, 'Temps CPU total (mesuré)', ...
        sprintf('%.3f s', t_cpu_elapsed), ...
        x_start + (card_w+gap), card_y, card_w, card_h, ...
        panel_bg, title_col, text_col);

    %  Carte 3 : Temps CPU pour 1 s simulée 
    make_card(fig, 'Temps CPU pour 1 s simulée', ...
        sprintf('%.2f min', cpu_time_for_1s/60), ...
        x_start + 2*(card_w+gap), card_y, card_w, card_h, ...
        panel_bg, title_col, text_col);

    %  Carte 4 : Puissance utilisée 
    make_card(fig, 'Puissance utilisée (PC)', ...
        sprintf('%.1f W', P_pc_W), ...
        x_start + 3*(card_w+gap), card_y, card_w, card_h, ...
        panel_bg, title_col, orange_col);

    %  Carte 5 : Facteur de ralentissement 
    make_card(fig, 'Facteur de ralentissement', ...
        sprintf('%.2fx', ratio_RT), ...
        x_start + 4*(card_w+gap), card_y, card_w, card_h, ...
        panel_bg, title_col, red_col);

    % 
    %  RANGÉE DE GRANDS ENCADRÉS (ligne 2) — y = 545
    %  [CO2 sim. actuelle] [CO2 pour 1 s] [CO2 pour 2 s] [Énergie 1 s]
    % 
    card_y2 = 545;

    %  Carte 5 : CO2 simulation actuelle 
    make_card(fig, 'CO2 — simulation actuelle', ...
        sprintf('%.6f gCO2e', co2_g), ...
        x_start, card_y2, card_w, card_h, ...
        panel_bg, title_col, green_col);

    %  Carte 6 : CO2 pour 1 s simulée 
    pC6 = make_card(fig, 'CO2 pour 1 s simulée', ...
        sprintf('%.4f gCO2e', co2_1s_g), ...
        x_start + (card_w+gap), card_y2, card_w, card_h, ...
        panel_bg, title_col, green_col);

    % Sous-label km dans la carte CO2 1 s
    uilabel(pC6, ...
        'Text',            sprintf('  %.6f km parcourus', eq_1s_km_car), ...
        'Position',        [10 5 card_w-20 22], ...
        'FontSize',        11, ...
        'FontWeight',      'normal', ...
        'FontColor',       [0.35 0.35 0.35], ...
        'BackgroundColor', panel_bg);

    %  Carte 7 : CO2 pour 2 s simulées 
    pC7 = make_card(fig, 'CO2 pour 2 s simulées', ...
        sprintf('%.4f gCO2e', co2_2s_g), ...
        x_start + 2*(card_w+gap), card_y2, card_w, card_h, ...
        panel_bg, title_col, green_col);

    uilabel(pC7, ...
        'Text',            sprintf('  %.6f km parcourus', eq_2s_km_car), ...
        'Position',        [10 5 card_w-20 22], ...
        'FontSize',        11, ...
        'FontWeight',      'normal', ...
        'FontColor',       [0.35 0.35 0.35], ...
        'BackgroundColor', panel_bg);

    %  Carte 8 : Énergie pour 1 s simulée 
    make_card(fig, 'Énergie pour 1 s simulée', ...
        sprintf('%.4f Wh', energy_1s_Wh), ...
        x_start + 3*(card_w+gap), card_y2, card_w, card_h, ...
        panel_bg, title_col, orange_col);

    % 
    %  PARTIE BASSE : TABLE MESURES (gauche) + TABLES DETAIL (droite)
    % 
    bot_y = 40;
    bot_h = 475;

    %  Table mesures CPU (gauche) 
    p_left = uipanel(fig, ...
        'Title',           'Mesures CPU et simulation', ...
        'Position',        [30 bot_y 640 bot_h], ...
        'BackgroundColor', panel_bg, ...
        'ForegroundColor', title_col, ...
        'FontWeight',      'bold');

    data_cpu = {
        'Modèle CPU',                 model_cpu;
        'Temps simulé [s]',           sprintf('%.8f', T_sim);
        'Pas de simulation [s]',      sprintf('%.2e', Ts_num);
        'Fréquence [Hz]',             sprintf('%.2e', Fs_num);
        'Nb de points estimé',        sprintf('%d', N_est);
        'Temps CPU total [s]',        sprintf('%.6f', t_cpu_elapsed);
        'Ratio CPU / temps réel',     sprintf('%.2fx', ratio_RT);
        'Ts effectif [s]',            sprintf('%.2e', Ts_reel);
        'Fs effectif [Hz]',           sprintf('%.2e', Fs_reel);
        'Nb de points réel',          sprintf('%d', N_reel);
        'RAM utilisée [MB]',          sprintf('%.1f', ram_utilisee_MB);
        'RAM totale PC [MB]',         sprintf('%.1f', ram_totale_MB);
        'Cœurs CPU disponibles',      sprintf('%d', cpu_coeurs);
        };

    uitable(p_left, ...
        'Data',        data_cpu, ...
        'ColumnName',  {'Mesure', 'Valeur'}, ...
        'ColumnWidth', {320, 265}, ...
        'Position',    [10 10 615 430], ...
        'FontSize',    13);

    %  Table énergie / CO2 (droite haut) 
    p_ener = uipanel(fig, ...
        'Title',           'Énergie et impact — simulation actuelle', ...
        'Position',        [690 bot_y+290 790 175], ...
        'BackgroundColor', panel_bg, ...
        'ForegroundColor', title_col, ...
        'FontWeight',      'bold');

    data_ener = {
        'Puissance estimée PC [W]',       sprintf('%.2f', P_pc_W);
        'Facteur CO2 Québec [gCO2/kWh]',  sprintf('%.2f', CO2_factor_g_per_kWh);
        'Énergie simulation [J]',         sprintf('%.6f', energy_J);
        'Énergie simulation [Wh]',        sprintf('%.8f', energy_Wh);
        'CO2 simulation [gCO2e]',         sprintf('%.9f', co2_g);
        };

    uitable(p_ener, ...
        'Data',        data_ener, ...
        'ColumnName',  {'Paramètre', 'Valeur'}, ...
        'ColumnWidth', {440, 300}, ...
        'Position',    [10 10 765 130], ...
        'FontSize',    13);

    %  Table projections (droite milieu) 
    p_proj = uipanel(fig, ...
        'Title',           'Projections à partir du ratio mesuré', ...
        'Position',        [690 bot_y+110 790 170], ...
        'BackgroundColor', panel_bg, ...
        'ForegroundColor', title_col, ...
        'FontWeight',      'bold');

    data_proj = {
        'Temps CPU pour 1 s simulée [s]',    sprintf('%.2f', cpu_time_for_1s);
        'Temps CPU pour 1 s simulée [min]',  sprintf('%.2f', cpu_time_for_1s/60);
        'Énergie pour 1 s simulée [Wh]',     sprintf('%.6f', energy_1s_Wh);
        'CO2 pour 1 s simulée [gCO2e]',      sprintf('%.6f', co2_1s_g);
        'Temps CPU pour 2 s simulées [min]', sprintf('%.2f', cpu_time_for_2s/60);
        'Énergie pour 2 s simulées [Wh]',    sprintf('%.6f', energy_2s_Wh);
        'CO2 pour 2 s simulées [gCO2e]',     sprintf('%.6f', co2_2s_g);
        };

    uitable(p_proj, ...
        'Data',        data_proj, ...
        'ColumnName',  {'Projection', 'Valeur'}, ...
        'ColumnWidth', {440, 300}, ...
        'Position',    [10 10 765 125], ...
        'FontSize',    13);

    %  Table équivalences CO2 (droite bas) 
    p_eq = uipanel(fig, ...
        'Title',           'Équivalences CO2 (approximations pédagogiques)', ...
        'Position',        [690 bot_y 790 100], ...
        'BackgroundColor', panel_bg, ...
        'ForegroundColor', title_col, ...
        'FontWeight',      'bold');

    data_eq = {
        'Simulation actuelle  km voiture essence',  sprintf('%.9f km',      eq_sim_km_car);
        '1 s simulée  km voiture essence',          sprintf('%.6f km',      eq_1s_km_car);
        '2 s simulées  km voiture essence',         sprintf('%.6f km',      eq_2s_km_car);
        '2 s simulées  charges smartphone',         sprintf('%.4f charges', eq_2s_phone_charges);
        };

    uitable(p_eq, ...
        'Data',        data_eq, ...
        'ColumnName',  {'Équivalence', 'Valeur'}, ...
        'ColumnWidth', {440, 300}, ...
        'Position',    [10 10 765 58], ...
        'FontSize',    13);

end

% 
%  HELPER : crée un encadré « carte KPI »
%  Retourne le uipanel pour pouvoir y ajouter des sous-labels
% 
function p = make_card(fig, titre, valeur, x, y, w, h, bg, title_col, val_col)
    p = uipanel(fig, ...
        'Title',           titre, ...
        'Position',        [x y w h], ...
        'BackgroundColor', bg, ...
        'ForegroundColor', title_col, ...
        'FontWeight',      'bold', ...
        'FontSize',        11);

    uilabel(p, ...
        'Text',            valeur, ...
        'Position',        [10 28 w-20 46], ...
        'FontSize',        22, ...
        'FontWeight',      'bold', ...
        'FontColor',       val_col, ...
        'BackgroundColor', bg);
end